const uz = {
    works: 'Kun yangiliklari',
    all: 'Hammasi',
    info1: 'Men veb va mobil ishlab chiqaruvchiman. Men 3 yildan beri veb-ishlab chiqaman. Men juda ko\'p veb-saytlar yaratdim va oxirgi veb-tizimda crm tizimini yaratdim. Hozir men react native da 5 ta mobil ilovani yaratmoqdaman. Hozir men yangi texnologiyalarni o\'rganmoqdaman. Men mobil etkazib berish dasturi bilan bir qatorda Internet-do\'kon mobil ilovasi ustida ishlayapman',
    info3: '\n'
        + ' \n'
        + '• Web Development  • Python  • Django Rest Framework • HTML5 • CSS3 • ReactJS • React Native • Bulma • Bootstrap • MySQL • English • PostgreSQL ',
    title1: 'Norov Nurshod',
    title2: 'Veb va IOS Android ishlab chiquvchisi',
    title3: 'Ko\'nikmalar',
    category: 'Kategoriyalar',
    rate: 'Reyting',
    page: 'Sahifalar',
    lang: 'Til',
    audioBook: 'Audio yangilik',
    notFount: 'Hozircha mavjud emas',
    readBook: 'Yangilikni o`qish',
    lit: 'Adabiyot',
    lingu: 'Tilshunoslik',
    history: 'Tarixiy',
    rel: 'Diniy',
    ethic: 'Axloqiy',
    disct: 'Lug`at',
    search: 'Qidirish...',
    notFountFavourite: 'Siz xozircha birorta ham yangilikni sevimlilar ro`yhatiga qo`shmadingiz 💔',
    settings: 'Sozlamalar',
    about: 'Nima haqida?',
    language: 'O\'zbek',
    changeLanguage: 'Tilni almashtirish',
}
const ru = {
    changeLanguage: 'Изменить язык',
    about: 'О чем?',
    notFountFavourite: 'Вы еще не добавили новости в свой список избранного 💔',
    lit: 'Литература',
    lingu: 'Лингвистика',
    history: 'История',
    rel: 'Религия',
    ethic: 'Этика',
    disct: 'Словарь',
    notFount: 'Пока недоступно',
    lang: 'Язык',
    rate: 'Рейтинг',
    works: 'Новости дня',
    all: 'Все',
    info1: 'Я производитель веб-сайтов и мобильных устройств. Я занимаюсь веб-разработкой 3 года. Я создал много веб-сайтов и создал систему crm в последней веб-системе. В настоящее время я создаю 5 мобильных приложений в React Native. В настоящее время я изучаю новые технологии. Я работаю над мобильным приложением для доставки, а также над мобильным приложением для интернет-магазина.',
    info3: '\n'
        + ' \n'
        + '• Web Development  • Python  • Django Rest Framework • HTML5 • CSS3 • ReactJS • React Native • Bulma • Bootstrap • MySQL • English • PostgreSQL ',
    title1: 'Норов Нуршод',
    title2: 'Веб-разработчик и разработчик iOS для Android',
    title3: 'Навыки и умения',
    category: 'Категории',
    page: 'Страницы',
    audioBook: 'Аудио новости',
    readBook: 'Читать новости',
    search: 'Поиск...',
    settings: 'Настройки',
    language: 'Русский',
}
const en = {
    changeLanguage: 'Change language',
    language: 'English',
    about: 'About what?',
    settings: 'Settings',
    notFountFavourite: 'You have not yet added any news to your list of favorites 💔',
    search: 'Search...',
    lit: 'Literature',
    lingu: 'Linguistics',
    history: 'History',
    rel: 'Religion',
    ethic: 'Ethics',
    disct: 'Dictionary',
    readBook: 'Read the news',
    notFount: 'Not yet available',
    audioBook: 'Audio book',
    lang: 'Language',
    page: 'Pages',
    rate: 'Rating',
    category: 'Categories',
    works: 'News',
    all: 'All',
    info1: 'I am a web and mobile manufacturer. I have been working in web development for 3 years. I have created a lot of websites and created a crm system in the last web system. I am currently creating 5 mobile apps in react native. I am currently learning new technologies. I am working on a mobile delivery app as well as an online store mobile app',
    info3: '\n'
        + ' \n'
        + '• Web Development  • Python  • Django Rest Framework • HTML5 • CSS3 • ReactJS • React Native • Bulma • Bootstrap • MySQL • English • PostgreSQL ',
    title1: 'Norov Nurshod',
    title2: 'Web and IOS Android developer',
    title3: 'Skills',

}

export const languages = { uz, ru, en }
